### ISSUE TITLE
Update documentation in README.md for all available options to pass to github actions

### ISSUE THREAD

**Issue by victor-frank-signet** [liquibase/github-action-generator#117]
I would like to be able to pass a --defaults-file to the github action workflow and/or additional command line arguments not present in liquibase-github-actions/update@v4.27.0. The documentation the github actions workflow README.md indicates that argument is not available, but looking at the code it is present.

Ref options:
https://github.com/liquibase-github-actions/update/blob/main/README.md
https://github.com/liquibase-github-actions/update/blob/main/action.yml

**Comment by jnewton03** [comment]
hi @victor-frank-signet , `--defaults-file` is a [global input](https://github.com/liquibase-github-actions/update/blob/main/README.md#optional-liquibase-global-inputs) available on all github actions.  Hope that helps!
