### ISSUE TITLE
update-testing-rollback does not seem to work

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/github-action-generator#59]
I noticed that _recently_ some bad _rollbacks_ were sneaking into our code base and passing our CI tests that use Liquibase.
In a nutshell, we test Liquibase scripts by applying changes, rolling back those changes, then applying them again.  If that succeeds, chances are that people have valid rollbacks defined.

Here is a simple example that is now passing:
```sql
-- liquibase formatted sql

-- changeset awhitford:create-simple-table
create table AW_SIMPLE (
  SIMPLE_ID int not null comment 'Simple Identifier',
  SIMPLE_DATE date not null comment 'Simple Date'
)
-- rollback drop table AW_DOES_NOT_EXIST_SHOULD_FAIL
```

I can see that the changeset is being applied, but I do not see any evidence that it is being rolled back and reapplied.
I am using `liquibase-github-actions/update-testing-rollback@v4.18.0`, but I have also tried older approaches and have witnessed the same issue -- rollbacks are not happening.

I feel like this must have been broken for a few months now, but I can't be certain.

⚠️ It appears that I am not the only one suffering from this:
* https://forum.liquibase.org/t/liquibase-rollback-acts-like-it-works-but-does-nothing/6132 🐛

**Comment by StevenMassaro** [comment]
We have a bug in our internal Jira board that reads very similar to this, and it's slated to be a part of our next sprint. For internal reference, it's DAT-7634.

**Comment by awhitford-cip** [comment]
🙏 Pretty please with sugar on top. 😃 

This is absolutely killing me because bad rollbacks are passing our CI tests.

**Comment by awhitford-cip** [comment]
As far as I can tell, v4.19 behaves the same as v4.18.  I don't recall what version started to fail; it has been months.  The problem was that I didn't notice it right away.  It is hard for me to rollback since I am now using some recent 4.19 features.

**Comment by jnewton03** [comment]
@filipelautert will take a look

**Comment by filipelautert** [comment]
Hello @awhitford-cip , one more thing: are you facing this problem using Oracle/MSSQL? Or any other database?

**Comment by awhitford-cip** [comment]
> Hello @awhitford-cip , one more thing: are you facing this problem using Oracle/MSSQL? Or any other database?

Right now, I am only using Snowflake, so I am unclear if this impacts other databases as well.
