### ISSUE TITLE
Checks Run in 4.19.0 throws: Unexpected argument(s): pro

### ISSUE THREAD

**Issue by Tylorjg** [liquibase/github-action-generator#61]
When using checks run in the 4.19.0 release, there is an error being thrown:

```
Unexpected argument(s): pro
For detailed help, try 'liquibase --help' or 'liquibase <command-name> --help'
Did you mean: rollback or future-rollback-from-tag-sql or rollback-sql?
```

When using 4.17.0, it works as expected.

Looking into this, found that 4.19.0 has `docker-entrypoint.sh "${GLOBALS[@]}" pro checks run "${PARAMS[@]}"`inside of the [checks run shell script](https://github.com/liquibase-github-actions/checks-run/blob/main/checks_run.sh). Whereas, 4.17.0 has `docker-entrypoint.sh "${GLOBALS[@]}" checks run "${PARAMS[@]}"` without **pro** as an argument.

Noticed that it was also inside of [checks show](https://github.com/liquibase-github-actions/checks-show/blob/main/checks_show.sh) where the **pro** argument is being added. Unsure how many files have the pro argument added.

**Comment by jnewton03** [comment]
Thank you for this report @Tylorjg.  We will investigate.

**Comment by mcred** [comment]
This is fixed [here](https://github.com/liquibase/github-action-generator/commit/bccec3f6fee3bb71c91c9ad4eaa79802a345afcc). All actions have been updated and those affected have been fixed, specifically [checks run](https://github.com/liquibase-github-actions/checks-run/blob/main/checks_run.sh).
