### ISSUE TITLE
Liquibase checks actions fail to update config file with new quality checks

### ISSUE THREAD

**Issue by mbohls** [liquibase/github-action-generator#62]
When a new version of Liquibase introduces additional quality checks, the liquibase checks commands automatically update the quality checks configuration file.  The liquibase checks actions fail when trying to create the backup configuration file /github/workspace/liquibase.checks-settings.conf.backup.01 because the /github/workspace directory does not exist.  The github action should create the “/github/workspace” directory and grant proper permissions so that the liquibase checks actions do not fail.

**Comment by jnewton03** [comment]
@filipelautert will take a look
