### ISSUE TITLE
Github actions are exposing hidden parameters

### ISSUE THREAD

**Issue by filipelautert** [liquibase/github-action-generator#85]
Github actions are exposing hidden parameters. For instance https://github.com/liquibase-github-actions/update shows the   `database: ""`  parameter,  whereas in the code it is marked as hidden:

```DATABASE_ARG = builder.argument("database", Database.class).hidden().build();```

Hidden parameters should not show as possible parameters to gh actions.

**Comment by kevin-atx** [comment]
@filipelautert - I assume you want me to add this issue to the next sprint as it is a security-related concern.

**Comment by kevin-atx** [comment]
Hey @mcred - could you review this issue and provide your feedback/guidance?

**Comment by mcred** [comment]
should be a minor update to not show hidden fields. What is the urgency on this?

**Comment by filipelautert** [comment]
@mcred IT's not that urgent - we just had one user trying to set up a value to hidden field and facing some issues, but we clarified with him on the gh issue. Those hidden fields usually are carrying internal objects thus won't work using github actions.

**Comment by filipelautert** [comment]
Fixed, thanks @mcred !
